FROM node:14.5-alpine

ARG port
ARG registry

# Clear the cache
# Install all build dependencies
# Add bash for debugging purposes
RUN rm -rf /var/cache/apk/* \
    && rm -rf /tmp/* \
    && apk update \
    && apk add --virtual --no-cache git make postgresql-client \
    && apk add --no-cache bash

# Create app directory
WORKDIR /usr/src/app

# Copy entire app over
ADD ./src/ ./

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY ./docker-entrypoint.sh /

# Remove unnecessary dirs
RUN rm -rf test

# Install all npm dependencies
RUN npm install --quiet --no-progress --registry=${registry:-https://registry.npmjs.org} && npm cache clean --force

EXPOSE $port

ENTRYPOINT ["/docker-entrypoint.sh"]

CMD ["start"]